/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BoxClientId": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "BoxClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CaldavPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CaldavUrl": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "CaldavUsername": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ClaudeCodeOAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordApplicationId": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "DiscordBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordHomeGuildId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordMonitoredChannels": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "DynamoDBEndpoint": {
      "type": "sst.sst.Linkable"
    }
    "DynamoDBRegion": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "DynamoDBTableName": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "EmailPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EmailUser": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ImapHost": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ImapPort": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "IsambardMemory": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "LogLevel": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "NodeEnv": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "PerchEnabled": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "PerchTestModeForceSlot": {
      "type": "sst.sst.Linkable"
    }
    "PerchTestModeTriggerOnStartup": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "Port": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "SmtpHost": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "SmtpPort": {
      "type": "sst.sst.Linkable"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}