/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ClaudeCodeOAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordApplicationId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordHomeGuildId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IsambardMemory": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "LogLevel": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "NodeEnv": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "Port": {
      "type": "sst.sst.Linkable"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}