/**
 * Centralized error codes for all Isambard errors.
 * Used for programmatic error identification and handling.
 */
// Stryker disable all: Enum values are static definitions
export enum ErrorCode {
    // Storage errors
    STORAGE_ERROR = 'STORAGE_ERROR',
    ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    DYNAMO_TIMEOUT = 'DYNAMO_TIMEOUT',

    // Memory tool errors
    MEMORY_TOOL_ERROR = 'MEMORY_TOOL_ERROR',
    PATH_NOT_FOUND = 'PATH_NOT_FOUND',
    PATH_ALREADY_EXISTS = 'PATH_ALREADY_EXISTS',
    INVALID_PATH = 'INVALID_PATH',
    TEXT_NOT_FOUND = 'TEXT_NOT_FOUND',
    CONTENT_TOO_LARGE = 'CONTENT_TOO_LARGE',
    TEXT_NOT_UNIQUE = 'TEXT_NOT_UNIQUE',
    INVALID_LINE_NUMBER = 'INVALID_LINE_NUMBER',

    // Reconciliation errors
    RECONCILIATION_ERROR = 'RECONCILIATION_ERROR',
    RECONCILIATION_THROTTLED = 'RECONCILIATION_THROTTLED',

    // Discord errors
    DISCORD_ERROR = 'DISCORD_ERROR',
    CHANNEL_NOT_FOUND_BY_ID = 'CHANNEL_NOT_FOUND_BY_ID',
    CHANNEL_NOT_ACCESSIBLE = 'CHANNEL_NOT_ACCESSIBLE',
    MESSAGE_FETCH_ERROR = 'MESSAGE_FETCH_ERROR',
    INVALID_SNOWFLAKE = 'INVALID_SNOWFLAKE',

    // Channel registry errors
    CHANNEL_REGISTRY_ERROR = 'CHANNEL_REGISTRY_ERROR',
    CHANNEL_NOT_FOUND_BY_NAME = 'CHANNEL_NOT_FOUND_BY_NAME',
    AMBIGUOUS_CHANNEL = 'AMBIGUOUS_CHANNEL',
    WELL_KNOWN_CHANNEL_NOT_FOUND = 'WELL_KNOWN_CHANNEL_NOT_FOUND',

    // Presence errors
    PRESENCE_ERROR = 'PRESENCE_ERROR',
    STATUS_GENERATION_ERROR = 'STATUS_GENERATION_ERROR',

    // State errors
    TRANSITION_ERROR = 'TRANSITION_ERROR',

    // Utility errors
    PATH_SECURITY_ERROR = 'PATH_SECURITY_ERROR',
    MEDIA_PROCESSING_ERROR = 'MEDIA_PROCESSING_ERROR',

    // Email errors
    EMAIL_ERROR = 'EMAIL_ERROR',
    CLASSIFIER_ERROR = 'CLASSIFIER_ERROR',
    EMAIL_PROCESSING_ERROR = 'EMAIL_PROCESSING_ERROR',
    WILDDUCK_ERROR = 'WILDDUCK_ERROR',
    WILDDUCK_AUTH_ERROR = 'WILDDUCK_AUTH_ERROR',

    // Bluesky errors
    BSKY_ERROR = 'BSKY_ERROR',
    BSKY_AUTH_ERROR = 'BSKY_AUTH_ERROR',
    BSKY_RATE_LIMIT_ERROR = 'BSKY_RATE_LIMIT_ERROR',
    BSKY_VALIDATION_ERROR = 'BSKY_VALIDATION_ERROR',

    // CalDAV errors
    CALDAV_ERROR = 'CALDAV_ERROR',
    CALDAV_AUTH_ERROR = 'CALDAV_AUTH_ERROR',
    CALDAV_FETCH_ERROR = 'CALDAV_FETCH_ERROR',
    CALDAV_TIMEOUT_ERROR = 'CALDAV_TIMEOUT_ERROR',
    CALDAV_AMBIGUOUS_MATCH = 'CALDAV_AMBIGUOUS_MATCH',

    // Contact errors
    CONTACT_NOT_FOUND = 'CONTACT_NOT_FOUND',
    CONTACT_LAST_IDENTIFIER = 'CONTACT_LAST_IDENTIFIER',
    CONTACT_NO_IDENTIFIERS = 'CONTACT_NO_IDENTIFIERS',
    BATCH_WRITE_EXHAUSTED = 'BATCH_WRITE_EXHAUSTED',

    // Browser errors
    BROWSER_ERROR = 'BROWSER_ERROR',
    BROWSER_NAVIGATE_TIMEOUT = 'BROWSER_NAVIGATE_TIMEOUT',

    // Memory-vec embedding errors
    MEMORY_VEC_ERROR = 'MEMORY_VEC_ERROR',
    MODEL_FILE_NOT_FOUND = 'MODEL_FILE_NOT_FOUND',
    INCOMPATIBLE_LLAMA_CPP = 'INCOMPATIBLE_LLAMA_CPP',
    EMBEDDER_CLOSED = 'EMBEDDER_CLOSED',

    // Vector index errors (SQLite-based semantic search)
    VECTOR_INDEX_ERROR = 'VECTOR_INDEX_ERROR',
    VECTOR_INDEX_CLOSED = 'VECTOR_INDEX_CLOSED',
    VECTOR_INDEX_UNAVAILABLE = 'VECTOR_INDEX_UNAVAILABLE',

    // Invariant violations (logic errors — should never be reached in correct code)
    INVARIANT_VIOLATION = 'INVARIANT_VIOLATION'

}
// Stryker restore all
